/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObjectsRouteImport } from './routes/objects'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObjectsObjectIdRouteImport } from './routes/objects_.$objectId'
import { Route as EventsEventIdRouteImport } from './routes/events_.$eventId'

const ObjectsRoute = ObjectsRouteImport.update({
  id: '/objects',
  path: '/objects',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsObjectIdRoute = ObjectsObjectIdRouteImport.update({
  id: '/objects_/$objectId',
  path: '/objects/$objectId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events_/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/events': typeof EventsRoute
  '/objects': typeof ObjectsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/objects/$objectId': typeof ObjectsObjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/events': typeof EventsRoute
  '/objects': typeof ObjectsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/objects/$objectId': typeof ObjectsObjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/events': typeof EventsRoute
  '/objects': typeof ObjectsRoute
  '/events_/$eventId': typeof EventsEventIdRoute
  '/objects_/$objectId': typeof ObjectsObjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contacts'
    | '/events'
    | '/objects'
    | '/events/$eventId'
    | '/objects/$objectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contacts'
    | '/events'
    | '/objects'
    | '/events/$eventId'
    | '/objects/$objectId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contacts'
    | '/events'
    | '/objects'
    | '/events_/$eventId'
    | '/objects_/$objectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactsRoute: typeof ContactsRoute
  EventsRoute: typeof EventsRoute
  ObjectsRoute: typeof ObjectsRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  ObjectsObjectIdRoute: typeof ObjectsObjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/objects': {
      id: '/objects'
      path: '/objects'
      fullPath: '/objects'
      preLoaderRoute: typeof ObjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects_/$objectId': {
      id: '/objects_/$objectId'
      path: '/objects/$objectId'
      fullPath: '/objects/$objectId'
      preLoaderRoute: typeof ObjectsObjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$eventId': {
      id: '/events_/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactsRoute: ContactsRoute,
  EventsRoute: EventsRoute,
  ObjectsRoute: ObjectsRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  ObjectsObjectIdRoute: ObjectsObjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
